language: csharp
mono: none
dotnet: 2.0.0

matrix:
  include:
    - os: linux
      dist: trusty     
    - os: osx

install:
  - dotnet restore gcs.core.sln

script:
 - dotnet build gcs.core.sln
 - dotnet test ./tests/gcs.UnitTests.core.csproj
